### ISSUE TITLE
RFC: Mission Statement

### ISSUE THREAD

**Issue by kcranston** [carpentries/executive-council-info#1]
# RFC for Mission Statement

A mission statement are the actions that we take to reach our vision. It should answer questions like these (from [this Forbes article](https://www.forbes.com/sites/patrickhull/2013/01/10/answer-4-questions-to-get-a-great-mission-statement/#7ffe5e6a67f5):

* What do we do?
* How do we do it?
* Whom do we do it for?
* What value are we bringing?

Here is the draft mission statement:

> The Carpentries builds global capacity in essential data and computational
> skills for conducting efficient, open, and reproducible research. We train and
> foster an active, inclusive, diverse community of learners and instructors
> that promotes and models the importance of software and data in research. This
> community collaboratively develops openly-available lessons and delivers these
> lessons using evidence-based teaching practices. We focus on people conducting
> and supporting research in diverse contexts including colleges, universities,
> and research labs.

Background:

The goal of this statement was to:

1. Capture our emphasis on building capacity for data and computational research
   by training and supporting people with the appropriate skills and perspectives.
2. Emphasize the importance of the community and that it is composed of both
   learners and instructors (often our members are both).
3. Describe our core activities.
4. Communicate our scope to serve as a guiding principle when making decisions
   about what activities to pursue (see a special note on this below).

Specific request for feedback:

The Executive Council struggled with the final sentence of this statement. The
goal of this sentence is to communicate the scope of The Carpentries to serve as
a guiding principle for where to commit our limited energy. For example, K-12
computing education is not currently a component of our mission. The goal is a
brief statement that communicates our general area of focus, which includes
colleges, universities, libraries associated with this institutions, and other
similar institutions (e.g., National labs). There is concern that the current
language of "research labs" incorrectly communicate a focus on science. We
considered making this more general by replacing “We focus on people conducting
and supporting research and scholarship”, but were concerned that it was
potentially too broad in terms of scope. We also considered "research
environments" and "research institutions" as substitutes for "research labs" but
weren't sure if either of these communicated well to the broad community. We
would very much like to hear feedback on this wording.

**Comment by swaldman3** [comment]
IMHO "research institutions" is inclusive - but I'm coming from a science background, so may not understand the concern.

**Comment by naupaka** [comment]
What about something to the effect of "...in diverse contexts, but focus primarily on..."?

**Comment by embray** [comment]
I feel like "research labs" also excludes things like libraries.  "Research institutions" is a bit more inclusive I think.

**Comment by embray** [comment]
> Is it worthwhile to explicitly say that "research" here is construed in a broad sense - not just the proverbial STEM?

I had assumed that to be the case myself, knowing the breadth of SWC/DC's mission.  But I agree that might be worth making explicit.

**Comment by jezcope** [comment]
I think national libraries and similar institutions also have a role to play and might or might not be regarded as "research institutions" depending on your context. "Research and cultural heritage institutions" might work bit it feels a bit too broad. It might have the side-effect of reassuring those in the humanities that they're not being sidelined though.

**Comment by gvwilson** [comment]
- "essential" => "foundational" or "fundamental" (if they really were essential, people would already have them)
- "promotes and models the importance of software and data in research" => I think this wants to be "software and data **skills**" ?
- "openly-available lessons" => "open access lessons" (because "open access" is a widely-used term)
- "in diverse contexts including colleges, universities, and research labs" => "in contexts such as colleges, universities, libraries, museums, and research labs" (since the word "diverse" is being used elsewhere to refer to diversity of community, and I think libraries and museums deserve a mention, even without Library Carpentry)

**Comment by jezcope** [comment]
I'm starting to wonder whether the key scoping thing is the people and what they're doing (doing or supporting research) rather than where they work. So I think listing a few contexts is useful, and I agree with @gvwilson's list, but I'm not sure how to emphasise that it's the people that matter most. Maybe 'who' as a joining word:

> We focus on people conducting and supporting research, who may work in contexts such as colleges, universities, libraries, museums, research labs or elsewhere.

**Comment by quirksahern** [comment]
Also, should we be sepcifying open as that is not always possible, but we still want people to use the same good practices

**Comment by quirksahern** [comment]
I like the term: “We focus on people conducting
and supporting research and scholarship”

**Comment by pitviper6** [comment]
I agree with @kariljordan - I've always thought mission statements should ideally be one sentence, maybe two. This means they are usually fairly broad, so you need to figure out what is the most important thing to drill down to specifics on. In The Carpentries case, I think that is building a community and the research angle. Granted, I just said in the vision statement thread that librarians don't do research, and we have a vibrant LC community. BUT! The metadata and secondary research liaison/reference librarians do fall into 'fostering research' through harnessing data to improve discoverability of data/other resources so in this context I think it's OK.
Something like this rough draft?

The Carpentries foster open, collaborative research through building an inclusive, diverse community of instructors and lesson materials to train learners in data and computational skills, focusing on members of research institutions.

**Comment by tkphd** [comment]
I really like this sentence:

> We train and foster an active, inclusive, diverse community of learners and instructors to promote and model the importance of software and data in research.

It's concise, well stated, and captures the optimism of The Carpentries mission. The rest of it is useful for background and clarification, but not as crucial as that one line.

**Comment by amyehodge** [comment]
Closing this issue as the Mission was approved and is included in our Handbook.
