### ISSUE TITLE
Motion to approve Sponsorship Model Task Force Charter

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#12]
The Carpentries Executive Council approves the Sponsorship Model Task Force Charter. 

We require a second for this motion (indicated in a comment below) prior to EC members voting with a thumbs up on this post.

**Comment by kcranston** [comment]
seconded!

**Comment by k8hertweck** [comment]
Waiting on votes from @rgaiacs @zjsteyn @mesfind @elliewix @kcranston (I know you seconded, Karen, but ya know, official thumbs up?)

**Comment by k8hertweck** [comment]
Motion passes, thanks folks! Minutes say @rgaiacs will start drafting charter for this task force, yes?

**Comment by amyehodge** [comment]
Motion was passed. Charter work is going on in another repo, [issue 48](https://github.com/carpentries-ec/conversations_ec_ed/issues/48).
