### ISSUE TITLE
Motion to approve policy of EC/CoCC liaison voting rights

### ISSUE THREAD

**Issue by elliewix** [carpentries/executive-council-info#13]
The Executive Council moves to accept the following guidelines regarding voting rights for the Executive Council (EC) liaison to the Code of Conduct Committee (CoCc):

* This policy will be reviewed during the the next (2020) Executive Council year.
* The EC liaison to the CoCc will normally abstain from voting on incident or procedural resolutions, but may vote as needed to ensure that an incident or other need can be responded to in a timely process. The chair of the CoCc will make this decision and indicate that the EC liaison vote will be necessary to resolve the incident within appropriate time.
* Should the EC liaison participate in a CoCc vote, and that resolution is appealed before the Executive Council, the liaison member will abstain from that appeal vote.

**Comment by k8hertweck** [comment]
I updated the language slightly to make the motion resemble our others, and also second!

**Comment by lexnederbragt** [comment]
I approve, but perhaps we can write all abbreviation out in full for those not familiar with them.

**Comment by elliewix** [comment]
Good call, I've edited it a bit to clarify the acronyms.

**Comment by amyehodge** [comment]
@elliewix I believe this is enough votes on this now
