### ISSUE TITLE
Motion to approve creation of 2 x 2 committee

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#14]
The Carpentries Executive Council approves the formation of a 2 x 2 Committee, which would bring together 2 people from each Lesson Program, 2 people from the Executive Council and 2 from staff, as a mechanism to share updates and information and discuss concerns. 

Please note this committee It is not meant to be a decision making group, but one that can share and bring information to the different decision making groups.

We require a second for this motion (indicated in a comment below) prior to EC members voting with a thumbs up on this post.

**Comment by amyehodge** [comment]
Seconded

**Comment by k8hertweck** [comment]
This motion has enough votes to pass; I'd like to include it in the next Carpentries newsletter if that is acceptable?

**Comment by amyehodge** [comment]
I think that would be great, thanks, @k8hertweck. @tracykteal do you see any reason not to include a note that we are planning to assemble this committee (or whatever we want to call it)?

**Comment by tracykteal** [comment]
Thanks, totally fine to include in the newsletter too.

**Comment by amyehodge** [comment]
Motion passed. Work on this in another repo on [issue 44](https://github.com/carpentries-ec/conversations_ec_ed/issues/44)
