### ISSUE TITLE
Add READMEs for directories

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#16]
Each subdirectory should include a README to explain the contents with more granularity than the main README

**Comment by amyehodge** [comment]
Agreed. They don't have to be much, but some explanation would be useful. For example, see the readme for the [Transparency Reports folder](https://github.com/carpentries/executive-council-info/tree/master/code-of-conduct-transparency-reports).

**Comment by k8hertweck** [comment]
Definitely links to relevant information, but also some mention of process: for example, meeting minutes are for regularly occurring monthly meetings, CoC reports are quarterly, etc. Also points of contact for individuals to email/tag for more information.

**Comment by amyehodge** [comment]
Group, could someone to volunteer to take on this task?

**Comment by zjsteyn** [comment]
Will take it on, @amyehodge proposed deadline?

**Comment by amyehodge** [comment]
@zjsteyn , by the meeting on August 15 would be great.

**Comment by k8hertweck** [comment]
I've added the two READMEs in question. These may need to be updated as we continue improving documentation, but this is sufficient for now.
