### ISSUE TITLE
Can we pin this repository?

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/executive-council-info#17]
As describe in https://github.blog/2016-06-16-pin-repositories-to-your-github-profile/.

**Comment by k8hertweck** [comment]
You mean to the [organization page](https://github.com/carpentries)? I would be tentatively supportive of that, although perhaps we should consider what other repos should be highlighted (currently it's only the website).

**Comment by amyehodge** [comment]
Agree with @k8hertweck. I think staff would need to be consulted about which things should be pinned, as there are quite a few repos and others may make more sense for the organization as a whole.

**Comment by maneesha** [comment]
I did pin The Carpentries website repo since that is our biggest repo used in our identity and communications with the world.  Beyond that I  agree that there should be a discussion about what we want to pin to reflect The Carpentries as a whole.

**Comment by jduckles** [comment]
In the `swcarpentry` org I created a meta repository back in 2016 to have a README that points people to things in the community and pinned it. This could be done for all carpentry organisations to help guide people who land on them in GitHub. https://github.com/swcarpentry/swcarpentry

**Comment by amyehodge** [comment]
@jduckles that is extremely helpful, and avoids the decision-making on pins, which are of a limited number and will almost certainly miss things.

**Comment by k8hertweck** [comment]
I'm resisting the urge to go ahead and fork that meta repo (which I'd really like to refer to as the MEGA REPO) and play around with it right now, but I think this is a great option.

**Comment by rgaiacs** [comment]
I am not a big fan of meta repositories because it yet another thing to maintain that will, eventually, have out of date information.

This repository has the minutes of the Executive Council meetings and the main way that the Executive Council report their work back to the community. This is why I think this repository should be pin in the organisation page.

**Comment by k8hertweck** [comment]
Since we tend to link to this repo from blog posts and the newsletter, it seems like the information is accessible enough as is without pinning or creating another repository to have to maintain.
