### ISSUE TITLE
Motion to approve the vision for The Carpentries

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#25]
The Carpentries Executive Council moves to accept the following statement as the vision for The Carpentries: **"The leading inclusive community teaching computing and data skills."**

This vision statement is modified from last year’s [public RFC on vision](https://github.com/carpentries/executive-council-info/issues/2). It effectively differentiates us from other groups engaging in training (i.e., "teaching computing and data skills"), while also focusing on core values and programs relevant to The Carpentries as a whole (i.e., "inclusive community"). We emphasize "leading" as a way to view our organization as both a growing organization, but also one that provides leadership in the space of computational training.  We look forward to Lesson Programs identifying their own more specific vision statements. 

EC members, please indicate your vote on this issue with a thumbs up or down after it has been seconded.

**Comment by kcranston** [comment]
Seconded!

**Comment by mesfind** [comment]
data skills or data science skills is nice?

**Comment by amyehodge** [comment]
@mesfind at this point we have closed the discussion on this. We are now voting on the statement as Kate has written it above, which does say "data skills." Note that you can give this a thumbs down to vote against, but a majority vote will carry it.

**Comment by amyehodge** [comment]
This motion has passed unanimously.
