### ISSUE TITLE
Motion: Executive Council Officers for 2020

### ISSUE THREAD

**Issue by amyehodge** [carpentries/executive-council-info#30]
I, Amy Hodge, move that we approve the following officer roles for the 2020 Executive Council:

Chair: Elizabeth Wickes
Vice Chair: Lex Nederbragt
Treasurer: Juan Steyn
Secretary: Joslynn Lee

Someone please second, and then all members of the NEW EC ONLY please use the thumbs up to indicate approval. Thanks.

**Comment by Cedric-Chambers** [comment]
Seconded!

**Comment by orchid00** [comment]
Seconded.
Thanks everyone for your work as officers

**Comment by amyehodge** [comment]
@Cedric-Chambers thanks for seconding. Please also remember to vote with the thumbs up on the original post at the top! :)

**Comment by amyehodge** [comment]
Hooray! This has been unanimously approved.
