### ISSUE TITLE
Motion: Strategic Plan Approval

### ISSUE THREAD

**Issue by amyehodge** [carpentries/executive-council-info#31]
I, Amy Hodge, move that we approve the final version of the Strategic Plan as laid out in [this document](https://docs.google.com/document/d/1Uf_-UaCKf52W51DpZYQ7LYaBXyZ1IrHXmt6nvivFRmk/edit#heading=h.o9m9xmt6gnj8).

Someone please second, and then all members of the OUTGOING EC ONLY please indicate your approval with a thumbs up. Thanks.

**Comment by kcranston** [comment]
Seconded!

**Comment by joslynnlee** [comment]
looks great!! I am excited about this!

**Comment by amyehodge** [comment]
Hooray! This has been unanimously approved.
