### ISSUE TITLE
Add nonverbal updates to November 2019 minutes

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#32]
@mesfind Could you add the nonverbal updates to the November minutes published [here](https://github.com/carpentries/executive-council-info/blob/master/minutes/2019/EC-minutes-2019-11-18.md)? Thank you!

**Comment by amyehodge** [comment]
I've added these. We should check to make sure they are there for the whole year. I'll put that on my list.

**Comment by amyehodge** [comment]
They are all there so far.
