### ISSUE TITLE
"police" or "policy" reports?

### ISSUE THREAD

**Issue by maneesha** [carpentries/executive-council-info#37]
In regards to [this fix](https://github.com/carpentries/executive-council-info/commit/d47cc5a788a120030a38357b457120d20f575b55)  is this supposed to be "police" or "policy" reports?  All past Code of Conduct Transparency Reports do include a section on Police Matters. There have been none, but I have taken this to mean that there were no incidents where we needed to involve law enforcement (police).

**Comment by konrad** [comment]
Thanks, Maneesha. I will change it back to "Police" and talk to the CoC Committee to be on the safe side.

**Comment by lexnederbragt** [comment]
What is the status of this issue? Can it be closed?

**Comment by maneesha** [comment]
The change was originally made by @serahrono.  
Tagging @carpentries/code-of-conduct-committee to verify the change.

**Comment by fmichonneau** [comment]
I believe that the correct word was "Police" and that's what is currently in use. Closing.
