### ISSUE TITLE
Add documentation for EC processes

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/executive-council-info#4]
We should include documentation here for things like:

- [x] timeline for regularly occurring EC events, like ED evals, financial reports, etc
- [x] descriptions of what needs to be updated when leadership changes, like GitHub, Google Drive, etc

This information is currently being drafted in Google Drive documents

**Comment by amyehodge** [comment]
@k8hertweck What's the status on this? Did we get all of this finished and, if so, can we links to the documents in this ticket? Thanks.

**Comment by k8hertweck** [comment]
There is a draft of the timeline, which I would be happy to add here.

The leadership changes are associated with onboarding/offboarding, for which @tracykteal has a more comprehensive list. Do we want to include that list here?

**Comment by k8hertweck** [comment]
I believe the two merged PRs above resolve this issue so it's ok to close.

**Comment by amyehodge** [comment]
Thanks.
