### ISSUE TITLE
Motion: minor changes to the Bylaws

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#40]
The EC moves to approve the changes made to the Bylaws between November 2018 and today without EC involvement. Changes can be seen here:

https://github.com/carpentries/docs.carpentries.org/commits/master/topic_folders/governance/bylaws.md

These changes were
- typos, spelling, title case etc
- adding help info to voting eligibility section (adding links to AMY)
- change 'Staff' to 'Core Team'

**Comment by orchid00** [comment]
Second motion

**Comment by amyehodge** [comment]
I don't see any of the changes other than the Staff to Core Team changes at https://github.com/carpentries/docs.carpentries.org/commit/f474f1d2f8d24c74a86c2419761ddfbe57406ee3. Can you point us to where we can see the others? Thanks.

**Comment by lexnederbragt** [comment]
Here is the full list:

Spelling:


https://github.com/carpentries/docs.carpentries.org/commit/56f6da221babdb3ba46efcdf0b8a3594d6a07314#diff-827b0c10902adcf798e77ba78efa441d

https://github.com/carpentries/docs.carpentries.org/commit/1c4abbc04ad5c99f974313deae441ee877d0b71f#diff-827b0c10902adcf798e77ba78efa441d



https://github.com/carpentries/docs.carpentries.org/commit/55cf4d1d68dffe73d949ab8b032985491a0ac18e#diff-827b0c10902adcf798e77ba78efa441d


Staff->Core team:

https://github.com/carpentries/docs.carpentries.org/commit/f474f1d2f8d24c74a86c2419761ddfbe57406ee3#diff-827b0c10902adcf798e77ba78efa441d

Add info about Amy:


https://github.com/carpentries/docs.carpentries.org/commit/8785b4102416f2a810472b46873a7d78c398645e#diff-827b0c10902adcf798e77ba78efa441d

**Comment by amyehodge** [comment]
Thanks so much, Lex.

**Comment by orchid00** [comment]
We can close this issue with 8 votes approving!
