### ISSUE TITLE
Motion: Small fixes to Bylaws document

### ISSUE THREAD

**Issue by orchid00** [carpentries/executive-council-info#42]
We are collecting small fixes to the Bylaws document, those that **do not change the meaning**.
In the following PR https://github.com/carpentries/2020_Bylaw_revision/pull/2

This is a motion for the EC to approve all those small fixes.

Note: For changes that need further discussion there are other issues in https://github.com/carpentries/2020_Bylaw_revision/

**Comment by lexnederbragt** [comment]
I second this motion

**Comment by orchid00** [comment]
This motion has been approved with 8 votes on June 18th,2020
Thanks Everyone @carpentries/executive-council
