### ISSUE TITLE
Motion: approving The Carpentries Committee Policy

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#43]
The Executive Council moves to approve The Carpentries Committee Policy as described in https://docs.google.com/document/d/1UEGzYNl_Mz3oz_j_Hk6NK7_BaZ5rZw8B9YYw8b_PoEY/edit.

After approval, these will be updated in the handbook.

**Comment by lexnederbragt** [comment]
Motion postponed awaiting an updated version of the document

**Comment by elliewix** [comment]
Process update:  Deadline of this week to get commentary into the google doc. Then the team will make the changes. When those have all been resolved and this is ready for voting, an email will be sent.

**Comment by kariljordan** [comment]
Does this motion include committee guidelines and task force guidelines?

- [The Carpentries Task Forces](https://docs.google.com/document/d/1N851QbE-_ejJqSNiqROvRVsTQo2K5ucNamwWBeaYzBA/edit)
- [Task Force Charter](https://docs.google.com/document/d/1tO3t5CM7Cs9s4HV_YoriQ5z9T9jKpXouAsDwyuZgQZ8/edit)

**Comment by lexnederbragt** [comment]
So far, committee guidelines only. We should have a separate process for Task Forces, I think.

**Comment by lexnederbragt** [comment]
Motion to be approved at the July EC meeting. Renamed to "Approving The Carpentries Committee Policy".
