### ISSUE TITLE
Motion: approving the Carpentries Task Force Policy

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#44]
The Executive Council moves to approve The Carpentries Task Force Policy as described in https://docs.google.com/document/d/1hnxSk1d-rmjZjS5ndJm2ZiHdf2eBRxCgEYa9PiPZoiY/edit.

After approval, these will be updated in the handbook.

**Comment by zjsteyn** [comment]
Second

**Comment by lexnederbragt** [comment]
Motion approved. Thanks!
