### ISSUE TITLE
Motion: Shifting the Executive Council Election 2021 time

### ISSUE THREAD

**Issue by konrad** [carpentries/executive-council-info#46]
Due to a delay in the required preparations the Executive Council shifts the election date of the Executive Council Election 2021 to the time frame starting from the Wednesday December 2 2020 to Thursday December 10, 2020 Anywhere on Earth.

**Comment by kariljordan** [comment]
Thank you for this!

**Comment by joslynnlee** [comment]
Thank you all for doing this!
