### ISSUE TITLE
Motion: approving the 2021 budget

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#50]
The Executive council moves to approve the 2021 budget as presented at the December 2020 council meeting.

**Comment by kariljordan** [comment]
Thanks Lex! Everyone should up vote by giving the thumbs up, correct?

**Comment by amyehodge** [comment]
Seconded.

**Comment by zjsteyn** [comment]
Thank you Lex

**Comment by lexnederbragt** [comment]
We have a majority. Motion passed. Thanks, everyone!
