### ISSUE TITLE
Motion to approve the 2021 EC officers and CoCc liaison (placeholder)

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#52]
The Executive council moves to approve the following officer roles and CoCc liaison for the 2021 Executive Council:

Chair: Lex Nederbragt
Vice Chair: Paula Andrea Martinez
Treasurer: Michael Smith
Secretary: Konrad Forstner
CoCc liaison: Konrad Forster (Masami takes over in three months)

**Comment by konrad** [comment]
Seconded.

**Comment by lexnederbragt** [comment]
Motion passed. Thanks everyone!
