### ISSUE TITLE
Motion to approve the EC Standing Committee structure, roles and responsibilities

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#53]
The Executive Council moves to approve the Executive Council Standing Committee structure, roles and responsibilities as described in the [proposal document](https://docs.google.com/document/d/1xVuA42zcIYMct09ynDq4Iz6txFVYthQuAHln_rMS2mI/edit?usp=sharing).

**Comment by smithmd5** [comment]
I second the motion.

**Comment by lexnederbragt** [comment]
Motion approved. Thanks!
