### ISSUE TITLE
Sponsored Instructor Training Proposal

### ISSUE THREAD

**Issue by kariljordan** [carpentries/executive-council-info#56]
This is Issue [#119](https://github.com/carpentries-ec/conversations_ec_ed/issues/119) in the EC's private repo. Adding the issue to the public repo so that the EC and Instructor Training Team can converse openly.

The Instructor Training Team (ITT) would like the Executive Council's Finance Committee to:

1. acknowledge that the ITT is moving forward with a "placeholder plan" for sponsored Instructor Training for 2021. 
2. take ownership of strategic planning for sponsorship of Instructor Training by reviewing the [Sponsored Instructor Training Proposal](https://docs.google.com/document/d/10du-3oxx54zMsvltwSN-aNY1w9FFHt8zPUJoiOPQGi8/edit#) and committing to driving decision making for this program, including it in the yearly EC timeline.

Related issue: https://github.com/carpentries-ec/conversations_ec_ed/issues/91

----------------------------------------------------
The Instructor Training Team has developed a [Sponsored Instructor Training Proposal](https://docs.google.com/document/d/10du-3oxx54zMsvltwSN-aNY1w9FFHt8zPUJoiOPQGi8/edit#). This document has two aims: 

1. to propose a procedure and schedule for annual strategic review and updating of the sponsored Instructor Training program to best serve the strategic growth priorities of The Carpentries, in cooperation with the Executive Council
2. to outline a plan for 2021 that represents an improvement to our current ad-hoc sponsorship program

The team is requesting the Finance Committee to review the proposal and:

1. acknowledge that the plan for 2021 is approved.
2. commit to strategic planning for sponsored Instructor Training moving forward, and developing a plan that we can review at the beginning of each fiscal year to set metrics/targets for sponsored Instructor Training.

Anyone on the EC is welcome to review and comment on the proposal, however, to prevent burnout, this is a matter for the **Finance Committee** to tackle.

I would like to transfer this repo from the private issue to the [Executive Council Info](https://github.com/carpentries/executive-council-info/) repo so that Karen (Instructor Training Team Lead) has access to your questions and comments. Please advise as to whether you'd like this issue to stay private (here), or if we can move it to the public repo.

**Comment by smithmd5** [comment]
Thanks Kari!

**Comment by kariljordan** [comment]
Copying the notes over from the private repo so that we can close this issue:

Per @smithmd5:

- Via consensus, the Finance Committee agreed during its 4/15 meeting to acknowledge the current ITT plan moving forward for 2021 (Bullet #1).
- Via consensus, the Finance Committee agreed during its 4/15 meeting to take ownership of strategic planning for sponsorship of Instructor Training by reviewing the Sponsored Instructor Training Proposal and committing to driving initial decision making for this program (Bullet #2).
