### ISSUE TITLE
Motion to approve the Executive Council Standing Committees charters for 2021

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#57]
The Executive Council moves to approve the Standing Committees Charters for 2021:

-   [Officers Committee](https://docs.google.com/document/d/11HBCWQpSztp94oCFen0FvJZlFYMq39_gnSAXYc4VSR8/edit#heading=h.4hekoriswwhv)
-   [Finance Committee](https://docs.google.com/document/u/0/d/18_7aHvIrzC6WYJtlSSFnfpz0blAQIIwiUtJ0M9KLYeM/edit)
-   [Program Committee](https://docs.google.com/document/d/1QA3O9B9BH7fVlYkDZMUyXejV1IL1bvyHM0r_XmuMyEo/edit#)
-   [Communication Committee](https://docs.google.com/document/d/1MyhIwvnuciS4jn_3JqF5OaV5zc3EZbrHlqrkVBDaXBo/edit#)
-   [Governance Committee](https://docs.google.com/document/d/1fG4lX_qLH5MjwNTnFeMq7UufwEDKq7dqckfAWuBnhb0/edit)

**Comment by chodacki** [comment]
Seconded

**Comment by lexnederbragt** [comment]
Motion passed. Thanks everyone!

**Comment by smithmd5** [comment]
Although the motion passed, I would like to make a friendly to the motion and list myself as the MAKER. The Executive Councul in whole cannot make a motion, a member of the council has to make the motion.  Please confirm acceptance.

Thanks,
Mike

**Comment by lexnederbragt** [comment]
Thanks, Mike! We have always formulated motions along the lines of "The Executive Council moves that ...". We also say, but not formally, that we follow "Robert's rules of engagement" at our meetings. During the 2020 Bylaw Revision, we had an [issue](https://github.com/carpentries/2020_Bylaw_revision/issues/16) to 'Describing “parliamentary procedures” for EC (and other?) meetings' that we didn't not resolve. I am interested in discussing these matters, including your comment here, further with the EC, and then would like to look at ["Marta's rules"](https://third-bit.com/files/2020/08/marthas/ -) also.
