### ISSUE TITLE
Motion to approve the Workflow for Urgent Public Statements

### ISSUE THREAD

**Issue by konrad** [carpentries/executive-council-info#62]
I move to approve the decision to use the [Workflow for Urgent Public Statements](https://docs.google.com/document/d/16nPzVkroVQL6BZdFRZFc5zZ8GfwBruWN7hGf9hXu6ss/edit?usp=sharing).

**Rationale**: Responses to issues whether public, smaller group or individually need to be value-driven. This rubric and workflow will enable us to act openly - have clear processes for how we manage statements; empower one another - making the reporting process accessible; ensuring that we keep people and our community first and that our statements also adhere to our core values.

**The scope of the workflow**: This workflow is intended for situations where an organisation that The Carpentries is affiliated with acts in a manner inconsistent with our values, or a larger societal issue arises that we feel compelled to issue a statement on. Individual actions and Code of Conduct (CoC) violations are best left to the existing CoC Committee and their existing workflow for investigation and reporting. 

**Workflow**: The workflow for public statements can only be used if incidents are formally reported/triggered. “Reported/triggered”, in this context means we have received an incident communication through established communication channels of The Carpentries: Slack, Twitter, Topicbox, LinkedIn, Facebook, e-mail, or other formal channel(s) established for this purpose. 

The workflow is documented in the document linked above.

**Comment by chodacki** [comment]
2nd.

**Comment by orchid00** [comment]
@konrad (comms committee et al) I have some questions (Keeping in mind, this motion is approved by the majority already. )
What is the main difference in the innitiation of this workflow with the CoC workflow. If an issue is publicly raised (on established  comms channels) and not reported to the CoC is it immediately part of this workflow? What are the characteristics of " incidents are formally reported/triggered". For example an unusual (racist/sexual/diminishing/etc) comment on social media is a trigger, but is that enough to open the workflow for urgent public statements? how is that not a CoC violation (maybe unreported)?

**Comment by konrad** [comment]
Thanks everybody - I will close this now.
