### ISSUE TITLE
Motion to Approve increase in FY2021 Annual Budget

### ISSUE THREAD

**Issue by smithmd5** [carpentries/executive-council-info#63]
Motion: I move to approve an increase in the FY2021 Annual Expense Budget from $2,064,301 to $2,150,953.

Hello fellow EC members!

During the June monthly treasury and finance call, Talisha shared an oversight in our Velocity fees that we did not budget for. There is an increase in the monthly fee paid versus what we budget.  Below Talisha has shared a budget adjustment explanation.

Once seconded, I vote in favor of this motion.

--- Suppoorting information

Our budget as it relates to Velocity expenses is in need of an update. In this new "[2021-06-10 Budget Adjustment" tab of our current budget document](https://docs.google.com/spreadsheets/d/1WjLrqB1ALZ73GM8pQItMpv1W5spWUfgVOM-7OlHyYt4/edit#gid=1355661256)", you will find a detailed description of the update as well as a comparison of the original and adjustment budget.

**Comment by lexnederbragt** [comment]
Seconded

**Comment by lexnederbragt** [comment]
Motion passed, closing
