### ISSUE TITLE
Motion to approve the Task Force Charter: Values Alignment Task Force

### ISSUE THREAD

**Issue by konrad** [carpentries/executive-council-info#64]
I move to approve the Task Force Charter: Values Alignment Task Force.

**Background and Objective**: The objective of this Task Force is to deliver a set of recommendations - a ‘[Due Diligence’ process](https://en.wikipedia.org/wiki/Due_diligence) - for approval by the Executive Council on how to identify whether an organisation or service is acting in accordance with The Carpentries [Core Values](https://carpentries.org/values/). These recommendations are to be used as checkpoints to check that the existing relationships and service providers are conforming and to verify that The Carpentries can safely enter into new relationships with organisations in the future. This may include establishing a separate long-term Committee (for example, “Values Committee”) to apply these recommendations.
This task originated in the question “Who should The Carpentries align ourselves with?” ([#109](https://github.com/carpentries-ec/conversations_ec_ed/issues/109)).

[Full document](https://docs.google.com/document/d/1aINZOJ04jSEC4EXL7-uucYQ8KpYRODSPU12YaBJHsF4/edit#) including suggestion for members of the task force

**Comment by lexnederbragt** [comment]
Seconded

**Comment by konrad** [comment]
This motion is approved. Thanks everybody!
