### ISSUE TITLE
Motion to expand the election policy to consider expertise for council elected positions

### ISSUE THREAD

**Issue by sstevens2** [carpentries/executive-council-info#66]
I move to expand election policy to include the following procedure for ensuring members of the the EC have varied expertise.

The Governance committee reviews the expertise of the community-elected seats and the standing EC members and then proposes a subset of expertises needed for the council-elected recommendations. Then the EC votes on that recommendation.  Feedback will be collected from EC CoreTeam before the Governance committee reviews the applications.
The information that is public to the community should contain a list of desired expertise (critical to being selected). Subset/slate will also include back-ups in case someone is unavailable. 

**Background**: This is related to the issue that arose with the last by-laws update about the voting methods for council-elected positions ([#108](https://github.com/carpentries-ec/conversations_ec_ed/issues/108)) and the proposed solution above was generated at the 2021 EC retreat.

**Comment by orchid00** [comment]
seconded

**Comment by orchid00** [comment]
This motion has passed with 7 votes
