### ISSUE TITLE
Motion to review EC needs prior to community elections

### ISSUE THREAD

**Issue by sstevens2** [carpentries/executive-council-info#67]
I move to expand election policy to include the following procedure for assessing the EC needs prior to election and including that information in the call for applications.

The EC will assess what needs they have for the upcoming election prior to putting out the call for community elected and council elected positions, including identifying the skills that are needed based on the standing EC and what we need for the Strategic plan.  Once identified these needs will be included in the call for applications for community elected positions.

Background: This is related to the issue that arose with the last by-laws update about the voting methods for council-elected positions (#108) and the proposed solution above was generated at the 2021 EC retreat.

**Comment by orchid00** [comment]
[Current 2021 unofficial election Policy](https://docs.google.com/document/d/1SjjD6o9Kfl-kCpSq_d2aMjjVr1ybyNcD/edit)
We do not need to call this a Policy if it is easier we can just call it Election Procedures

**Comment by orchid00** [comment]
Really good comment from Mike: specific expertise are included in the election

**Comment by orchid00** [comment]
this one motion has been made redundant with the passing of issue 66 https://github.com/carpentries/executive-council-info/issues/66
