### ISSUE TITLE
Motion to approve the instructor training sponsorship strategy for 2021-2022

### ISSUE THREAD

**Issue by kariljordan** [carpentries/executive-council-info#68]
**I move to approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022.**

Overview: The Carpentries have offered sponsored instructor training to individuals through our Open Instructor Training program. While this program has demonstrated a similar success to those trained through memberships, we understand that groups are important to building sustainable communities. We have on occasion, and by request, sponsored groups through instructor training. We are planning to begin the formalisation of this offering to improve accessibility, which will also support our strategic goals and grant deliverables. Given the financial implications of sponsored activities and the strategic operational implications of where training is sponsored, we are requesting the approval and advice of the Executive Council.

Request(s): We have the following requests for the Executive Council -

- Approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022
- Advise on the identified regional and diversity targets for sponsored instructor training in 2021-2022

Proposed Programmatic Period: October 1, 2021    - December 31, 2022

**Comment by smithmd5** [comment]
Thank you, Kari.

I move to approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022. If Kari is original maker of the motion, I second.

Mike

**Comment by chodacki** [comment]
I second

**Comment by kariljordan** [comment]
@orchid00 asked to make a friendly to the motion to include the regional and diversity targets. @smithmd5 can you revise your motion?

**Comment by smithmd5** [comment]
Friendly motion accepted.

I move to approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022 to support meeting regional and diversity targets.

**Comment by karenword** [comment]
In Kari's correspondence, she indicates that this motion makes sponsorship seats contingent upon satisfying diversity targets, such that 100% of sponsored seats will be expected to meet those targets. However, in the evaluation section of the proposal document, we propose a metric of 80% of sponsored training seats meeting regional and diversity targets for 2021-2022 as a goal. This implies that some sponsored activities that do not meet these targets would still be expected, and that we would report on progress towards our goal upon review in 2022. 

Are we only authorized to sponsor training seats that meet our targets, or are we authorized to sponsor training seats, with priority for events that support our targets?

**Comment by smithmd5** [comment]
Hi Karen (et al):

100% of the 250 seats to the regional and diversity targets was NOT my
understanding or intent with the motion. I took the friendly to be that we
include targets in the consideration of seat placements.

Working to clarify the motion and actions forward with the EC.

Thanks,
Mike

**Comment by smithmd5** [comment]
Greetings EC members!

After reviewing the full motion string in GitHub, I have noted that eight (8) EC members voted for the original motion listed as "I move to approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022." with explanation to support the motion.

When scrolling down to where the friendly motion was made to add the supplemental text regarding the regional and diversity targets, you will note that only one person voted for the friendly.

Given that GitHub is used for EC voting, and assuming we still follow standard rules for voting regarding the percentage of affirmative (thumbs up) votes required for a vote (or friendly to a vote) to pass, essentially I would conclude that the friendly to the original motion did not pass.

Thus the vote on the original motion still stands. With this in mind, an amendment to the friendly is not required as the friendly to the motion did not pass (per the GitHub vote).

I would recommend that we simply update the minutes to this meeting to list the original motion as the official motion and that is passed. The supplemental commentary in the GitHub issue supports our intent as an EC for the target to be strongly considered in filling the approved 250 seats, but are not the only considerations or requirements for filling the seats.

To make my feedback official, I will copy into the GitHub issue as well. I believe this issue can be closed once we update the minutes to the original motion.

Respectfully submitted.  To make it official, I welcome EC members to provide a thumbs up in approval to this response.

Thanks,Mike

**Comment by lexnederbragt** [comment]
Hi all,

I had to look up 'friendly motion' as it is a new thing to me. Rereading this issue and its comments leave me a bit confused, and I suspect I am not the only one. I think it would be good - albeit cumbersome - to approve a new motion making it absolutely clear what we have voted on and approved. Would that be an acceptable course of action?

As an aside, we earlier discussed writing down (our own version of) our 'parliamentary procedures', describing how we submit, word and approve motions, during and inbetween meetings, including amending them. Maybe we should revisit this issue...

**Comment by smithmd5** [comment]
Hi Lex,

If we want to "redo" the motion for clarity, that is fine. My last comments
were essentially that the original motion (without the friendly text added)
still stands, as once the friendly text was added, I was the only person
that voted on the friendly. Given no one else voted on the friendly version
of the motion, the friendly motion did not pass. Thus the original motion
is still in place. so there would be no further action. If you want to
initiate the same motion or a new motion with clarifying text, that can
work as well.

Mike

**Comment by kariljordan** [comment]
Greetings! It has been more than one month since the initial motion and our Instructor Training Team is not clear on what the approved motion is. They would like to move forward. Can we get this resolved during our meeting today?

**Comment by smithmd5** [comment]
Hi Kari,

Yes, we can resolve the issue today. My stance is the original motion
stands. The program has diversity and regional targets that take priority
consideration in acceptance, but are not the ONLY targets for acceptance.
Any other members of The Carpentries community or others that are typically
allowed access can still be considered and accepted.

I can add these comments to the issue in GitHub if needed to resolve. The
only discussion that we need to ensure consensus today is to understand
that the targets are not exclusive, but priority targets for consideration
and do not exclude others that are not within the targets from applying and
being accepted.

Thanks,
Mike

**Comment by smithmd5** [comment]
During the August meeting of the EC, the motion below was unanimously approved (9 votes) by the EC.

**I move to approve the sponsorship limit of 250 seats for sponsored instructor training in 2021-2022.**

Maker: Michael S.
Second: John C.

The assignment of the 250 approved seats will be managed by the Core Team, with priority consideration given to our identified diversity and regional targets for the sponsored instructor training program.
