### ISSUE TITLE
Motion to expand voting eligibility for the 2022 EC election

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/executive-council-info#69]
Please delete this line and the text below before submitting your contribution.

**Comment by lexnederbragt** [comment]
[apologies for accidentally clicking submit]

As per our discussions regarding this issue, there is a strong wish from the Core Team to temporarily relax the voting eligibility requirements for the 2022 EC election in light of the pandemic. Core Team wrote:

> Due to the global pandemic and the low numbers of instructors signing up to teach, we will be extending the  deadline required for instructors to teach to be able to vote. Instructors who have taught 2 times between 2019 and 2021 will be eligible to vote in the next Executive Council elections. 

Formally, this goes against stipulations in [our Bylaws](https://docs.carpentries.org/topic_folders/governance/bylaws.html#eligibility-rights-and-termination-for-voting-members). A quick discussion in the officers Committee about this can be summarised as follows (and I am quoting some of it literally):

Bylaws withstanding, we should ask ourselves "what is in the best interest of The Carpentries and our membership?". Bylaws are guidelines, but in the history of any organization, there are times when exceptions to the rules are needed because NEW situations arise that were unforeseen. As the Executive Council, we can act in the best interest, including votes to amend or temporarily suspend a Bylaws rule for a specified period of time and/or for a specific reason.... or not.

Based on this discussions I have put my reservations about a motion to allow the temporary relaxation of the bylaws aside in the interest of the community.

The motion thus sounds as follows:

I move that, for the 2022 election for Executive Council, the conditions for individual membership, as described in the [Bylaws](https://docs.carpentries.org/topic_folders/governance/bylaws.html#eligibility-rights-and-termination-for-voting-members), are extended as follows: Certified instructors who have taught 2 times between 2019 and 2021 are eligible for Voting Membership

Note that the other conditions from the Bylaws for individual membership are not changed or affected by this motion.

Please someone second and vote using the usual thumbs up/down emoji.

**Comment by chodacki** [comment]
Seconded.

**Comment by lexnederbragt** [comment]
Motion passed. Thanks everyone!
