### ISSUE TITLE
Motion: ratifying the 2022 Executive Council for The Carpentries

### ISSUE THREAD

**Issue by orchid00** [carpentries/executive-council-info#70]
The Executive Council ratifies the 2022 Executive Council in accordance with the results of the Community and Council elections.

Yanina Bellini Saibene [Elected since 2022]
Konrad Förstner [Elected since 2022]
Annajiat Alim Rasel [Appointed since 2022]
Amel Ghouila [Appointed since 2022]

John Chodacki [Appointed since 2021]
Aleksandra Nenadic [Elected since 2021]
Michael Smith [Appointed since 2021]
Sarah Stevens [Elected since 2021]
Masami Yamaguchi [Appointed since 2021]

Following a second, please vote with a thumbs up or down.
We need this motion to publish the blog post.

**Comment by chodacki** [comment]
Seconded

**Comment by orchid00** [comment]
Passed motion
