### ISSUE TITLE
Motion to update the Lesson Program Governance

### ISSUE THREAD

**Issue by anenadic** [carpentries/executive-council-info#71]
I move to approve the following proposal for the [new Lesson Program Governance policy](https://docs.google.com/document/d/1be6V7lw9BdbHSObNBQFhxHTtb8CIsrDFXInCAlHS0T4/edit).
 
Under the proposal, each Lesson Program (currently Software, Data and Library Carpentry) will have a Lesson Program Governance Committee, which will comply with the general committee policy as described in the Carpentries Handbook. Each Lesson Program Governance Committee will look after and serve its sub-community as well as determine what constitutes the curriculum and core curriculum for (each of) its workshop(s) together with the corresponding Curriculum Advisory Committee(s). A Lesson Program can thus have one or more Curriculum Advisory Committees responsible for each of its workshops (e.g. in the case of Data Carpentry which has different domain specific workshops and serves various sub-communities).

**Comment by sstevens2** [comment]
Seconded

**Comment by lexnederbragt** [comment]
Closing as we will use in-meeting voting on motions instead of through GitHub for the 2021-12-21 EC meeting. (Sorry for not communicating this clearly enough)
