### ISSUE TITLE
Motion to approve officer roles

### ISSUE THREAD

**Issue by kcranston** [carpentries/executive-council-info#9]
We approve the following officer roles for the 2019 Executive Council: 
* Amy Hodge as Chair
* Kate Hertweck as Vice-chair
* Raniere Silva as Treasurer
* Mesfin Diro as Secretary

Moved by Karen Cranston, seconded by Raniere Silva

**Comment by rgaiacs** [comment]
I seconded it.

**Comment by kcranston** [comment]
Approved unanimously! Welcome to our new ~~overlords~~ officers.
